sass scss/theme1.scss theme1.css
sass scss/theme2.scss theme2.css
sass scss/theme3.scss theme3.css
sass scss/theme4.scss theme4.css
sass scss/theme5.scss theme5.css
sass scss/theme6.scss theme6.css
sass scss/theme7.scss theme7.css
sass scss/theme8.scss theme8.css
sass scss/theme9.scss theme9.css
sass scss/theme10.scss theme10.css
sass scss/theme11.scss theme11.css
sass scss/theme12.scss theme12.css
sass scss/theme13.scss theme13.css
sass scss/theme14.scss theme14.css
sass scss/theme15.scss theme15.css
sass scss/theme16.scss theme16.css
sass scss/theme17.scss theme17.css
sass scss/theme18.scss theme18.css